runtime: php72
instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.70
  min_instances: 1
  max_instances: 5
  min_pending_latency: 30ms
  max_pending_latency: automatic

handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)
